# Configuration snippet for vdr-vaapivideo                               -*- sh -*-
#
# Add command line options to pass to the vaapivideo plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-vaapivideo*/README.md for info about available options.

PLUGIN_OPTIONS=""
